### ISSUE TITLE
Consider dropping Java 8 source compat

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo#314]
Right now, we require the Lyo code to be Java 8 compatible even though we dropped JDK 8 support just in case, so that if we need to backport some fixes to the old versions and make a bugfix release, we don't need to deal with backporting Java 11 code to a Java 8 codebase.

I think this is unnecessary. Some projects plan to drop Java 11 support this fall when JDK 21 LTS is released and to support JDK 17 and JDK 21. Also, we didn't make any such releases on Lyo 2.x. Also, making bugfix releases to Lyo <5.0 is going to be problematic due to a need to backport fixes for Jena CVEs to a fork (to be made) of an older Jena version.

Suggestion: update https://github.com/eclipse/lyo/blob/35ce053a7af430b3a74018dc46cd1d93e23d542f/pom.xml#L14-L16 to use Java 11 language level.

**Comment by jamsden** [comment]
Agree.


From: Andrew Berezovskyi ***@***.***>
Reply-To: eclipse/lyo ***@***.***>
Date: Thursday, April 27, 2023 at 11:43 AM
To: eclipse/lyo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [eclipse/lyo] Consider dropping Java 8 source compat (Issue #314)

Right now, we require the Lyo code to be Java 8 compatible even though we dropped JDK 8 support just in case, so that if we need to backport some fixes to the old versions and make a bugfix release, we don't need to deal with backporting Java
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Right now, we require the Lyo code to be Java 8 compatible even though we dropped JDK 8 support just in case, so that if we need to backport some fixes to the old versions and make a bugfix release, we don't need to deal with backporting Java 11 code to a Java 8 codebase.

I think this is unnecessary. Some projects plan to drop Java 11 support this fall when JDK 21 LTS is released and to support JDK 17 and JDK 21. Also, we didn't make any such releases on Lyo 2.x. Also, making bugfix releases to Lyo <5.0 is going to be problematic due to a need to backport fixes for Jena CVEs to a fork (to be made) of an older Jena version.

Suggestion: update https://github.com/eclipse/lyo/blob/35ce053a7af430b3a74018dc46cd1d93e23d542f/pom.xml#L14<https://github.com/eclipse/lyo/blob/35ce053a7af430b3a74018dc46cd1d93e23d542f/pom.xml#L14> to use Java 11 language level.
