### ISSUE TITLE
JSTL 1.2 dependency is Vulnerable to XML External Entity (XXE) Injection 

### ISSUE THREAD

**Issue by rahulbhadauriya** [eclipse/lyo#47]
Security team has performed 3rd party vulnerability scan for a OSLC connector and found that dependency used in OAuth Web App JSTL 1.2 is Vulnerable to XML External Entity (XXE) Injection attack.

Published vulnerabilities:
CVE-2015-0254 , CVSS score HIGH(7.5):
Apache Standard Taglibs before 1.2.3 allows remote attackers to execute arbitrary code or conduct external XML entity (XXE) attacks via a crafted XSLT extension in a (1) <x:parse> or (2) <x:transform> JSTL XML tag. <a href="http://cwe.mitre.org/data/definitions/611.html" target="_blank">CWE-611: Improper Restriction of XML External Entity Reference ('XXE')</a>

File Path: WEB-INF/lib/jstl-1.2.jar

Here are recommendations from Security team:
Remediation:
Do one of the following:
    1. Update the library to a newer version that doesn't have the reported vulnerability
    2. Explain why the issue doesn't apply

Check the following to make sure that the replacement does not appear in the NVD or CVE database as vulnerable:
    1. https://nvd.nist.gov/vuln/search?search_type=all&cves=on
    2. http://cve.mitre.org/cve/search_cve_list.html

 References:
        - Reports of jstl-1.2.jar as vulnerable to XXE:
               * https://snyk.io/vuln/SNYK-JAVA-JAVAXSERVLET-30449
               * https://nvd.nist.gov/vuln/detail/CVE-2015-0254

**Comment by berezovskyi** [comment]
1. We are not going to backport a fix to 2.4.0 unless someone does the maintenance work, we will only aim to fix it in 4.0.
1. The issue does not apply as Lyo does not use  <x:parse> or (2) <x:transform>  at all.
1. I think the right fix is to use https://mvnrepository.com/artifact/javax.servlet.jsp.jstl/javax.servlet.jsp.jstl-api/1.2.2 and not to include any implementation since Servlet 3.0 includes JSTL: https://stackoverflow.com/questions/2151075/cannot-load-jstl-taglib-within-embedded-jetty-server#3172395

**Comment by berezovskyi** [comment]
Replaced with JSTL API in https://github.com/eclipse/lyo/commit/b8567089ee6b10315df401aa010cf84102d617d9#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R152
