### ISSUE TITLE
Update and Migrate the Lyo Wiki from Eclipse to Github

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo#8]
We need to migrate any active Wiki pages from Eclipse wiki (https://wiki.eclipse.org/Lyo) to Github.

I see 2 alternatives: (@jamsden @berezovskyi I would like your opinion on this)
1. https://github.com/eclipse/lyo is only a launch point for related wikies. Wiki pages are managed udner the respective github repo of the Lyo project. (for example, Lyodesigner pages are under https://github.com/eclipse/lyo.designer/wiki)
2. We consolidate ALL wiki pages under https://github.com/eclipse/lyo. Under the respective github repo, we can have ONLY developer-related wiki pages. But end-user documentation for ALL our repositories are consolidated to https://github.com/eclipse/lyo

Irrespective, This are the initial action points:
1. Move this current front page (https://github.com/eclipse/lyo) to “repositories” or “working from source”.
1. Move the the content from https://wiki.eclipse.org/Lyo to this front page https://github.com/eclipse/lyo.
1. Move following pages from Eclipse-wiki to https://github.com/eclipse/lyo.core 
    - https://wiki.eclipse.org/Lyo/General_Setup_for_OSLC4J_Development
    - https://wiki.eclipse.org/Lyo/creating_OSLC4J_project
1. Create a simple Client page under (here, or under https://github.com/eclipse/lyo.client?)

**Comment by jamsden** [comment]
I see little motivation for fragmenting our developer collaboration and 
use documentation across eclipse and GitHub. Since we committed to moving 
the source in order to reduce development overhead and simplify 
contribution, we should do the same for the Wikis. 

We could distinguish three types of documentation:

1. Developer collaboration (e.g., all the notes I typically take when 
doing development)
2. Generally useful documentation for developer, user or other stakeholder 
explanations and use
3. End user documentation - which is typically published documentation 
with well through out navigation

I think the GitHub Wikies are fine for items 1 and 2 with a little care in 
the Wiki organization.

GitHub Wikies maybe don't scale as well for 3), end user documentation. We 
could continue using the OSLC Developer Guide GitHub Pages for this: 
http://oslc.github.io/developing-oslc-applications/



Jim Amsden, Senior Technical Staff Member
OSLC and Linked Lifecycle Data
919-525-6575

**Comment by jadelkhoury** [comment]
But the aim is indeed to move from Eclipse wiki to GitHub wiki. We agree on that? 

If so, my question is where on GitHub should we put the wiki pages, given that we have so many repositories and hence many wikis (each repo has its own wiki) 

And now I found out that there is yet another GitHub wiki page -  the OSLC Developer Guide: http://oslc.github.io/developing-oslc-applications/ 

Ahhh...

**Comment by berezovskyi** [comment]
So, I think Jad and Jim are saying the same thing in different ways. I won't go too crazy with the Github wikis as Jim says in §3. I still think a standalone website is much better for the long-term, eg

https://docusaurus.io/en/ (many JS components use it)
http://dynalon.github.io/mdwiki/#!index.md (I did some initial experiments with this one, quite nice)
https://www.vogella.com/tutorials/AsciiDoc/article.html (all Spring and RedHat docs use that)

Having said that, I do suggest not using Wikis for the "root" repo, let's just move all the content from the Eclipse wiki to the README of eclipse/lyo. Let's also move the developer info over to the wikis on the right repos.

But I think Jad is most interested in the user-facing content. Because me and Jim agree on using HTML site generators for §3, a have two questions then:

1. Which of those three generators shall we use? Or should we use Jekyll which is the default for Github?
2. Shall we deploy the generated docs to Github Pages or Eclipse? The latter will be a bit harder.

**Comment by jamsden** [comment]
We already have a lot of content on OSLC Developer Guide using GitHub 
pages, which use Harp and Jade: 
https://ines.io/blog/the-ultimate-guide-static-websites-harp-jade. Unless 
there's a compelling reason to change, and resources available to migrate 
existing content, why not stick with that?


Jim Amsden, Senior Technical Staff Member
OSLC and Linked Lifecycle Data
919-525-6575

**Comment by berezovskyi** [comment]
Harp & Jade it is then.

**Comment by jadelkhoury** [comment]
Jade must be good, but I have no idea what it is.
@berezovskyi will you be able to update me on how to update this site then during the week (face to face)?

**Comment by berezovskyi** [comment]
I have no idea myself, but let's take it next week maybe? We'll need to read that guide.

FTR, Harp sources are under https://github.com/OSLC/developing-oslc-applications/tree/gh-pages/_harp

@jamsden why does the parent directory includes all the generated HTML? Wasn't GH supposed to do that anyway?

**Comment by berezovskyi** [comment]
just had a chat with @jadelkhoury:

1. How to make hierarchy on the left to mimic the Eclipse Wiki? @jamsden 
2. Why not merge http://oslc.github.io/developing-oslc-applications/ with open-services.net? That's for Axel and Gabriel to consider.

**Comment by jamsden** [comment]
Unfortunately http://oslc.github.io/developing-oslc-applications/ and 
open-services.net use different technologies. 

Jim Amsden, Senior Technical Staff Member
OSLC and Linked Lifecycle Data
919-525-6575

**Comment by jadelkhoury** [comment]
https://open-services.net/resources/developing-oslc-applications/ on open-services seems to be a copy of http://oslc.github.io/developing-oslc-applications/

If we deal with the difference in technology, it would be beneficial to consolidate content under one place. 
Wouldn’t it be good to have this “developer corner” under open-services instead?

**Comment by jamsden** [comment]
Ideal, but a significant transformation of content. 

https://open-services.net/resources/developing-oslc-applications/ does not 
include any of the iotp-adaptor documentation I added.


Jim Amsden, Senior Technical Staff Member
OSLC and Linked Lifecycle Data
919-525-6575

**Comment by gabrielfdac** [comment]
How about [gitbook ](https://www.gitbook.com/) as a platform for all OSLC documentation?

It supports github integration and seems like a nice solution for this case. 

In fact Solid is using it for a part of their [docs](https://solid.gitbook.io/solid-hacks/)

We could host it in the open-services website or separately (linking from the main website) and for open source projects [see pricing](https://www.gitbook.com/pricing).

While it would definitely involve time and effort to make the transition, it seems like it could potentially save time later down the line, as well as unify the documentation. Having different version or copies of the same documentation, to me, seems like a bad idea and extra work to guarantee all documents are available and have the same content in all places.

Just an option to consider as a "hub" of sorts for all OSLC docs.

**Comment by jadelkhoury** [comment]
to move on on this topic, I have just made a first step in migrating some Lyo wiki pages to http://oslc.github.io/developing-oslc-applications/.

Please see my pull request https://github.com/OSLC/developing-oslc-applications/pull/4.

It does not answer all ideas we suggested here, but at least some of the stuff I am convinced we need to do.

**Comment by berezovskyi** [comment]
Thanks a lot, Jad! I think this is an excellent first step!

**Comment by jadelkhoury** [comment]
thanks @berezovskyi 

@jamsden I'd like to have your say on this patch also, given that you've been behind the whole site so far. So it would be good if the changes are still consistent with your intended structure.

**Comment by jadelkhoury** [comment]
I believe we are done with this issue.
